---
title: "Dashboards for PUBPOL 543"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
```

[comment]: # two plot here with fade effect

Life Expectancy Rates 
=====================================

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Life Expectancy Box Plot

```{r}
readRDS("WorldLifeExpectancyBP.rds")
```

### Life Expectancy Histogram

```{r}
readRDS("WorldLifeExpectancy.rds")
```

[comment]: # two plot here

Women's Fertility Rates by Continent
=====================================

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Female Fertility Rates Box Plot

```{r}
readRDS("WomenFertilityRatesWorldWideBP.rds")
```

### Female Fertility Rates Histogram

```{r}
readRDS("WomenFertilityRatesWorldWide.rds")
```

[comment]: # Three maps here

Various Worldwide Metrics
=====================================

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Carbpm Dioxide Emissions Map

```{r}
readRDS("CDEmissionsbyCountry.rds")
```

### Industrial Production Growth Map

```{r}
readRDS("IPGrowthbyCountry.rds")
```

### Labor Force Map

```{r}
readRDS("LFbyCountry.rds")
```